train:
  _target_: torch.utils.data.ConcatDataset
  datasets:
    - _target_: src.datasets.LibrispeechDataset
      part: "train-clean-360"
      data_dir: null
      instance_transforms: ${transforms.instance_transforms.train}
      max_audio_length: 16.0
      max_text_length: 256
    - _target_: src.datasets.LibrispeechDataset
      part: "train-clean-100"
      data_dir: null
      instance_transforms: ${transforms.instance_transforms.train}
      max_audio_length: 16.0
      max_text_length: 256

val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  data_dir: null
  instance_transforms: ${transforms.instance_transforms.inference}
