train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-clean-100"
  data_dir: null
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  data_dir: null
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  data_dir: null
  instance_transforms: ${transforms.instance_transforms.inference}
