train:
  _target_: torch.utils.data.ConcatDataset
  datasets:
    - _target_: src.datasets.LibrispeechDataset
      part: "train-clean-360"
      data_dir: null
      instance_transforms: ${transforms.instance_transforms.train}
    - _target_: src.datasets.LibrispeechDataset
      part: "train-clean-100"
      data_dir: null
      instance_transforms: ${transforms.instance_transforms.train}
    - _target_: src.datasets.LibrispeechDataset
      part: "train-other-500"
      data_dir: null
      instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  data_dir: null
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  data_dir: null
  instance_transforms: ${transforms.instance_transforms.inference}
