test:
  _target_: torch.utils.data.ConcatDataset
  datasets:
    - _target_: src.datasets.librispeech_dataset.LibrispeechDataset
      part: "test-other"
      instance_transforms: ${transforms.instance_transforms.inference}
