train: []
inference:
  - _target_: src.metrics.BeamSearchCERMetric
    name: "CER_(BeamSearch)"
    beam_width: 10
  - _target_: src.metrics.BeamSearchWERMetric
    name: "WER_(BeamSearch)"
    beam_width: 10
