train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.BeamSearchCERMetric
    name: "CER_(BeamSearch)"
  - _target_: src.metrics.BeamSearchWERMetric
    name: "WER_(BeamSearch)"
