train:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.spec_augs.spec_augment.SpecAugment
        freq_mask_param: 40
        time_mask_param: 15
        p: 0.9
inference:
  data_object:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Normalize1D
        mean: 0.5
        std: 0.5
