defaults:
  - model: conformer
  - writer: cometml
  - metrics: example
  - datasets: example
  - dataloader: librispeech
  - transforms: example_only_instance
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  betas: [0.9, 0.98]
  eps: 1e-9
  weight_decay: 1e-4
lr_scheduler:
  _target_: src.optim.transformer_scheduler.TransformerLRScheduler
  d_model: 144
  warmup_steps: 4000
  factor: 0.5
loss_function:
  _target_: src.loss.CTCLossWrapper
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
trainer:
  log_step: 50
  evaluate_step: 10 # iterations
  n_epochs: 50
  epoch_len: 6501
  device_tensors: ["spectrogram", "spectrogram_length", "text_encoded"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min val_WER_(BeamSearch)" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  decoding_strategy: "beam_search" # "argmax" or "beam_search"
  beam_search_beam_width: 10
