defaults:
  - model: conformer_M_bpe
  - writer: cometml
  - metrics: universal
  - datasets: finetune
  - dataloader: librispeech
  - transforms: finetune_augs_p1
  - _self_

optimizer:
  _target_: torch.optim.AdamW
  lr: 1  #3e-4
  betas: [0.9, 0.98]
  eps: 1e-9
  weight_decay: 1e-6

lr_scheduler:
  _target_: src.optim.noam_lr.NoamLR
  d_model: 256
  warmup_steps: 4000
  factor: 0.5

loss_function:
  _target_: src.loss.CTCLossWrapper
  blank: 0
  reduction: 'mean'
  zero_infinity: true

text_encoder:
  _target_: src.text_encoder.BPETextEncoder
  model_path: "bpe_model.model"

trainer:
  log_step: 50
  n_epochs: 200
  epoch_len: 400  # null = use full dataset
  device_tensors: ["spectrogram", "spectrogram_length", "text_encoded"] # which tensors should be on device (ex. GPU)
  resume_from: null  # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min val_WER" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  decoding_strategy: "argmax" # "argmax", "beam_search", or "beam_search_lm"
  beam_search_beam_width: 10
  max_grad_norm: 10.0
