defaults:
  - model: conformer
  - writer: cometml
  - metrics: inference
  - datasets: inference
  - dataloader: librispeech
  - transforms: example_only_instance
  - _self_

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder

inferencer:
  device_tensors: ["spectrogram", "spectrogram_length", "text_encoded"]
  device: auto
  save_path: "librispeech_predictions"
  seed: 1
  from_pretrained: "saved/testing/model_best.pth"
  save_dir: "saved"
  run_name: "librispeech_inference"
  decode_method: "argmax"  # "argmax" or "beam_search"
  beam_width: 10
