defaults:
  - model: baseline
  - metrics: example
  - datasets: custom_dir
  - dataloader: custom_dir
  - transforms: example_only_instance
  - _self_

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder

inferencer:
  device_tensors: ["spectrogram", "spectrogram_length", "text_encoded"]
  device: auto
  save_path: "custom_dir_predictions"
  seed: 1
  from_pretrained: "saved/testing/model_best.pth"
  save_dir: "saved"
  run_name: "custom_dir_inference"
