train:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_mels: 80         # changed from 128 -> 80 (article)
    n_fft: 1024
    hop_length: 160

  audio:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.gain.Gain
        min_gain_in_db: -2
        max_gain_in_db: 3
        p: 0.25

inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_mels: 80         # changed from 128 -> 80 (article)
    n_fft: 1024
    hop_length: 160
