train:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_mels: 128
    n_fft: 512
    hop_length: 160

  audio:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.gain.Gain
        min_gain_in_db: -6.0
        max_gain_in_db: 3.5
        p: 0.5

      - _target_: src.transforms.wav_augs.pitch_shift.PitchShift
        sample_rate: 16000
        min_transpose_semitones: -4.0
        max_transpose_semitones: 6.0
        p: 0.5

      - _target_: src.transforms.wav_augs.speed.Speed
        min_speed: 0.85
        max_speed: 1.15
        p: 0.5

      - _target_: src.transforms.spec_augs.spec_augment.SpecAugment
        freq_mask_param: 40
        time_mask_param: 15
        p: 0.9

inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_mels: 128
    n_fft: 512
    hop_length: 160
